// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'btnWrapper': string;
  'buttons': string;
  'buttons_shifted': string;
  'header': string;
}
declare var cssExports: CssExports;
export = cssExports;
