// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'details': string;
  'element': string;
  'flex': string;
  'retry': string;
  'title': string;
}
declare var cssExports: CssExports;
export = cssExports;
