// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'action-item': string;
  'content': string;
  'defaultValue': string;
  'draggableItem': string;
  'dragging': string;
  'dropZone': string;
  'editableInput': string;
  'extraItems': string;
  'handle': string;
  'icon': string;
  'imagePreview': string;
  'menu': string;
  'moreOptions': string;
  'moreOptionsButton': string;
  'name': string;
  'popoverContent': string;
  'popoverPortal': string;
  'rtl': string;
}
declare var cssExports: CssExports;
export = cssExports;
