// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'button_header': string;
  'info_body': string;
  'waiting_spinner': string;
}
declare var cssExports: CssExports;
export = cssExports;
