// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'anchor': string;
  'anchorContainer': string;
  'patContainer': string;
  'patInput': string;
  'status': string;
  'step': string;
  'wsContainer': string;
}
declare var cssExports: CssExports;
export = cssExports;
