// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'patContainer': string;
  'patInput': string;
  'wsContainer': string;
}
declare var cssExports: CssExports;
export = cssExports;
