name: Release
on:
  push:
    branches:
      - ya-build
jobs:
  build:
    name: Build Project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - uses: actions/setup-node@v2
        with:
          node-version: '12.18.1'
      - name: Git Unshallow
        run: git fetch --prune --unshallow
      - name: Fetch Node Packages
        run: |
          yarn
      - name: Build
        run: |
          yarn build
        env:
          NODE_ENV: production
