name: Pre-Release
on:
  push:
    branches:
      - '*'
      - '!master'

jobs:
  pre_release_bin:
    name: Pre-Release Binaries
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Git Unshallow
        run: git fetch --prune --unshallow
      - name: Get Release Details
        id: release_details
        uses: botpress/gh-actions/get_release_details@master
      - name: Fix Change Log
        id: changelog
        run: echo "::set-output name=value::${{ steps.release_details.outputs.changelog }}"
      - name: Fetch Node Packages
        run: |
          yarn
      - name: Extract Branch Name
        id: extract_branch
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      - name: 'Build and Package'
        run: |
          yarn build --prod
          yarn package
      - name: Rename Binary Files
        uses: botpress/gh-actions/rename_binaries@master
      - name: 'Release'
        uses: softprops/action-gh-release@v1
        with:
          files: ./bin/studio*
          prerelease: true
          draft: false
          body: ${{ steps.changelog.outputs.value }}
          name: ${{ steps.extract_branch.outputs.branch }}
          tag_name: pre-${{ steps.extract_branch.outputs.branch }}
          target_commitish: ${{ steps.extract_branch.outputs.branch }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
