name: Pre-Release
on:
  push:
    branches:
      - '*'
      - '!master'

jobs:
  pre_release_bin:
    name: Pre-Release Binaries
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Git Unshallow
        run: git fetch --prune --unshallow
      - name: Get Release Details
        id: previous_tag
        uses: botpress/gh-actions/get_release_details@master
      - name: Show info
        run: |
          echo ${{ steps.previous_tag.outputs.tag }}
          echo ${{ steps.previous_tag.outputs.isNewRelease }}
      - name: Test changelog
        id: build_changelog
        uses: botpress/gh-actions/build_changelog@master

      - name: Fetch Node Packages
        run: |
          echo ${{ steps.build_changelog.outputs.changelog }}
          yarn
      - name: Extract Branch Name
        id: extract_branch
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      - name: 'Build and Package'
        env:
          GITHUB_EVENT: ${{ toJson(github.event) }}
        run: |
          echo ${{ steps.previous_tag.outputs.tag }}
          yarn build --prod
          yarn package
      - name: Rename Binary Files
        uses: botpress/gh-actions/rename_binaries@master
      - name: 'Release'
        uses: softprops/action-gh-release@v1
        with:
          files: ./bin/studio*
          prerelease: true
          draft: false
          body: ${{ steps.build_changelog.outputs.changelog }}
          name: ${{ steps.extract_branch.outputs.branch }}
          tag_name: ${{ steps.extract_branch.outputs.branch }}
          target_commitish: ${{ steps.extract_branch.outputs.branch }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
