name: Pre-Release
on:
  push:
    branches:
      - '**'
      - '!master'

jobs:
  pre_release_bin:
    name: Build and Publish Binaries
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@master

      - name: Get yarn cache directory path
        id: yarn-cache-dir
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Configure Caching
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Extract Branch Name
        id: extract_branch
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"

      - name: Git Unshallow
        run: git fetch --prune --unshallow

      - name: Get Release Details
        id: release_details
        uses: botpress/gh-actions/get_release_details@master

      - name: Fetch Node Packages
        run: yarn

      - name: Build Project
        run: yarn build --prod

      - name: Package Binaries
        run: yarn package

      - name: Rename Binary Files
        uses: botpress/gh-actions/rename_binaries@master

      - name: Create Pre-Release
        uses: softprops/action-gh-release@v1
        with:
          files: ./bin/studio*
          prerelease: true
          name: ${{ steps.extract_branch.outputs.branch }}
          tag_name: dev-${{ steps.extract_branch.outputs.branch }}
          target_commitish: ${{ steps.extract_branch.outputs.branch }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
