name: Pre-Release
on:
  push:
    branches:
      - '*'
      - '!master'

jobs:
  pre_release_bin:
    name: Pre-Release Binaries
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Fetch Node Packages
        run: |
          yarn
      - name: Get Previous Tag
        id: previous_tag
        shell: bash
        run: |
          last_tag=$(node -e "require('.github/workflows/code/latest_release_tag.js').getLastTags().then(cl => console.log(cl))")
          echo $last_tag
          echo "::set-output name=last_tag::$last_tag"
      - name: Test output
        run: |
          echo name: ${{ steps.previous_tag.outputs.last_tag  }}
      - name: Extract Branch Name
        id: extract_branch
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      - name: 'Build and Package'
        env:
          GITHUB_EVENT: ${{ toJson(github.event) }}
        run: |
          echo name: ${{ steps.previous_tag.outputs.tag  }}
          yarn build --prod
          yarn package
          node .github/workflows/code/rename_binary.js
      - name: 'Release'
        uses: softprops/action-gh-release@v1
        with:
          files: ./bin/studio*
          prerelease: true
          draft: false
          name: ${{ steps.extract_branch.outputs.branch }}
          tag_name: ${{ steps.extract_branch.outputs.branch }}
          target_commitish: ${{ steps.extract_branch.outputs.branch }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
