name: Release
on:
  push:
    branches:
      - '*'
      - '!master'

jobs:
  release_bin:
    name: Pre-Release Binaries
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: test
        env:
          EVT: ${{ toJson(github.event) }}
        run: |
          node .github/workflows/code/rename_binary.js
      - name: Fetch Node Packages
        run: |
          yarn
      - name: Get Current Version
        id: extract_version
        uses: Saionaro/extract-package-version@v1.0.6
      - name: Validate Semver
        id: validate_semver
        run: |
          valid_current_version=$(node ./node_modules/semver/bin/semver.js ${{ steps.extract_version.outputs.version }})

          echo $valid_current_version
          echo "::set-output name=valid_current_version::$valid_current_version"
      # - name: 'Build and Package'
      #   run: |
      #     yarn build --prod
      #     yarn package
      #     node .github/workflows/code/rename_binary.js
      # - name: 'Release'
      #   uses: softprops/action-gh-release@v1
      #   with:
      #     files: ./bin/studio-v*
      #     prerelease: true
      #     draft: false
      #     body: 'Branch build'
      #     name: v${{ steps.validate_semver.outputs.valid_current_version }}
      #     tag_name: v${{ steps.validate_semver.outputs.valid_current_version }}
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
