name: Release
on:
  push:
    branches:
      - '*'
      - '!master'

jobs:
  release_bin:
    name: Pre-Release Binaries
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Fetch Node Packages
        run: |
          yarn
      - name: Get Current Version
        id: extract_version
        uses: Saionaro/extract-package-version@v1.0.6
      - name: Extract Branch Name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: Validate Semver
        id: validate_semver
        run: |
          valid_current_version=$(node ./node_modules/semver/bin/semver.js ${{ steps.extract_version.outputs.version }})

          echo $valid_current_version
          echo "::set-output name=valid_current_version::$valid_current_version"
      - name: 'Build and Package'
        env:
          GITHUB_EVENT: ${{ toJson(github.event) }}
        run: |
          yarn build --prod
          yarn package
          node .github/workflows/code/rename_binary.js
      - name: 'Release'
        uses: softprops/action-gh-release@v1
        with:
          files: ./bin/studio*
          prerelease: true
          draft: false
          body: 'Branch build'
          name: br-${{ steps.extract_branch.outputs.branch }}
          tag_name: br-${{ steps.extract_branch.outputs.branch }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
