name: Pre-Release
on:
  push:
    branches:
      - '*'
      - '!master'

jobs:
  pre_release_bin:
    name: Pre-Release Binaries
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Git Unshallow
        run: git fetch --prune --unshallow
      - name: Rename bin
        uses: botpress/studio/.github/workflows/code/rename_binaries@ya-branch-bin
        with:
          path: .lol
      - name: Fetch Node Packages
        run: |
          yarn
      - name: Extract Branch Name
        id: extract_branch
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      - name: 'Build and Package'
        env:
          GITHUB_EVENT: ${{ toJson(github.event) }}
        run: |
          yarn build --prod
          yarn package
          node .github/workflows/code/rename_binary.js
      - name: 'Release'
        uses: softprops/action-gh-release@v1
        with:
          files: ./bin/studio*
          prerelease: true
          draft: false
          name: ${{ steps.extract_branch.outputs.branch }}
          tag_name: ${{ steps.extract_branch.outputs.branch }}
          target_commitish: ${{ steps.extract_branch.outputs.branch }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
