name: Pre-Release
on:
  pull_request:
    - types: [ready_for_review]

jobs:
  pre_release_bin:
    if: github.event.pull_request.draft == false
    name: Build and Publish Binaries
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@master

      - uses: actions/setup-node@v1
        with:
          node-version: '12.18.1'

      - name: Install python3
        uses: actions/setup-python@v1
        with:
          python-version: '3.x'
          architecture: 'x64'

      - name: Install Tools
        run: |
          pip install awscli

      - name: Git Unshallow
        run: git fetch --prune --unshallow

      - name: Get Release Details
        id: release_details
        uses: botpress/gh-actions/get_release_details@master

      - name: Fetch Node Packages
        run: yarn

      - name: Build Project
        run: yarn build
        env:
          NODE_ENV: production

      - name: Package Binaries
        run: yarn package

      - name: Extract Informations
        id: info
        uses: botpress/gh-actions/extract_info@master

      - name: Rename Binary Files
        uses: botpress/gh-actions/rename_binaries@master

      - name: Publish Binaries
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws s3 sync bin s3://botpress-dev-bins/studio/${{ steps.info.outputs.branch_sanitized }}
