name: Pre-Release
on:
  push:
    branches:
      - '**'
      - '!master'

jobs:
  pre_release_bin:
    name: Build and Publish Binaries
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@master

      - name: Install python3
        uses: actions/setup-python@v1
        with:
          python-version: '3.x'
          architecture: 'x64'
      - name: Install Tools
        run: |
          pip install awscli

      - name: Extract Branch Name
        id: extract_branch
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"

      - name: Git Unshallow
        run: git fetch --prune --unshallow

      - name: Get Release Details
        id: release_details
        uses: botpress/gh-actions/get_release_details@master

      - name: Fetch Node Packages
        run: yarn

      - name: Build Project
        run: yarn build --prod

      - name: Package Binaries
        run: yarn package

      - name: Rename Binary Files
        uses: botpress/gh-actions/rename_binaries@master

      - name: Publish Binaries
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws s3 sync bin s3://botpress-dev-bins/studio/${{ steps.extract_branch.outputs.branch }}
