name: Release
on:
  push:
    branches:
      - master
jobs:
  release_bin:
    name: Release Binaries
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Git Unshallow
        run: git fetch --prune --unshallow
      - name: Fetch Node Packages
        run: |
          yarn
      - name: Get Release Details
        id: release_details
        uses: botpress/gh-actions/get_release_details@dev
      - name: Fix Change Log
        id: changelog
        run: echo "::set-output name=value::${{ steps.release_details.outputs.changelog }}"
      - name: 'Build and Package'
        if: ${{ steps.release_details.outputs.is_new_release }}
        run: |
          yarn build --prod
          yarn package
      - name: 'Release'
        if: ${{ steps.release_details.outputs.is_new_release }}
        uses: softprops/action-gh-release@v1
        with:
          files: ./bin/studio-v*
          prerelease: false
          draft: false
          body: ${{ steps.changelog.outputs.value }}
          name: v${{ steps.release_details.outputs.version }}
          tag_name: v${{ steps.release_details.outputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
