name: Codestyle
on: [push]
jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: '12.18.1'
      - name: Install Dependencies
        run: |
          yarn
      - name: Run Tests
        run: |
          yarn test
